# Generated by Django 6.0.1 on 2026-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('numTel', models.CharField(max_length=40)),
                ('prixNuit', models.CharField(max_length=50)),
                ('devise', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
            ],
        ),
    ]
