# Generated by Django 6.0.2 on 2026-02-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
